language: go

go:
  - 1.7
  - 1.8
  - tip

os:
  - linux
  - osx

install:
  - go get github.com/smartystreets/goconvey/convey
  - go get
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g npm@4.0.2


script:
  - go build
  - go test -v ./...
  - cd app
  - npm install
  - npm run build
