PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS `images` (
  `id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `path`	TEXT NOT NULL UNIQUE,
  `link`	TEXT NOT NULL UNIQUE,
  `mime` TEXT NOT NULL,
  `hash` TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS `artists` (
  `id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `name`	TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "albums" (
  `id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `name`	TEXT NOT NULL UNIQUE,
  `cover_id`	INTEGER,
  `year`	INTEGER,

  FOREIGN KEY(`cover_id`) REFERENCES `images`(`id`)

);
CREATE TABLE IF NOT EXISTS "songs" (
  `id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `name`	TEXT NOT NULL,
  `artist_id`	INTEGER,
  `album_id`	INTEGER,
  `year`	INTEGER,
  `genre`	TEXT,
  `duration` REAL,
  `mime`	TEXT NOT NULL,
  `path`	TEXT NOT NULL,
  `cover_id`	INTEGER,
  `played` INTEGER NOT NULL,

  FOREIGN KEY(`artist_id`) REFERENCES `artists`(`id`),
  FOREIGN KEY(`album_id`) REFERENCES `albums`(`id`),
  FOREIGN KEY(`cover_id`) REFERENCES `images`(`id`)
);

CREATE TABLE IF NOT EXISTS `users` (
  `id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `username`	TEXT NOT NULL UNIQUE,
  `password`	TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `playlists` (
  `id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `name`	TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS `playlist_songs` (
  `id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  `playlist_id`	INTEGER NOT NULL,
  `song_id`	INTEGER NOT NULL,

  FOREIGN KEY(`playlist_id`) REFERENCES `playlists`(`id`) ON DELETE CASCADE,
  FOREIGN KEY(`song_id`) REFERENCES `songs`(`id`) ON DELETE CASCADE,

  UNIQUE(`playlist_id`, `song_id`)
);
